### ISSUE TITLE
Improved documentation

### ISSUE THREAD

**Issue by LukasMahieu** [MAGICS-LAB/DNABERT_S#1]
Hey,

Cool work, thanks for the codebase!
It would be helpful to include a small train_debug.csv inside the repository, so you can see what the input data should look like and test the code without having to download and inflate the full training data.
Also, the argument "datapath" is, from my understanding, simply the path to the folder where your csv files are stored. So calling it "a dict of data" (in the parser) or the "path to the data dict" (in the README) is confusing, since this makes the user start looking for some unmentioned json/dictionary.

**Comment by WeiminWu2000** [comment]
Thanks, we will modify it.
