### ISSUE TITLE
Requirements need to be supplemented

### ISSUE THREAD

**Issue by Wesady** [MAGICS-LAB/DNABERT_S#10]
After I execute `pip install -r requirements.txt`, there are still some dependency errors:
```
from textblob.translate import NotTranslated
ModuleNotFoundError: No module named 'textblob.translate'
```
But I already have installed `textblob`. It can be fixed by `pip install textblob==0.17.1`.
Another error is
```
import gensimfrom scipy.linalg import get_blas_funcs, triu
File "/home/gpu0/miniconda3/envs/reads_classifier/lib/python3.9/site-packages/gensim/__init__.py", line 11, in <module>
ImportError: cannot import name 'triu' from 'scipy.linalg' 
```
It can be fixed with `conda install scipy==1.10.1`.

**Comment by Zhihan1996** [comment]
Thanks for indicating this! I have change the file accordingly.
