### ISSUE TITLE
Can you provide fine-tuning code

### ISSUE THREAD

**Issue by Wesady** [MAGICS-LAB/DNABERT_S#11]
Hi!
DNABERT-S is a brilliant model and I want to use it to do meta genetic short reads classification. I want to use data of my interested species to do fine-tuning, but I can't find code for fine-tuning, could you provide it or some strategy?
THANK YOU!

**Comment by Zhihan1996** [comment]
Hey,

Thanks for your interest in our work. We did not intend to use the model in a fine-tuning way so we did not provide fine-tune scripts here. But you can find out a fine-tune scripts at [https://github.com/MAGICS-LAB/DNABERT_2](https://github.com/MAGICS-LAB/DNABERT_2).

It's super simple to use:
1. change the model_name_or_path to `zhihan1996/DNABERT-S`
2. prepare your dataset into a csv file following the example.
