### ISSUE TITLE
Clustering and binning

### ISSUE THREAD

**Issue by yazhinia** [MAGICS-LAB/DNABERT_S#15]
Hello,
      Thank you for providing a great language model that can be applied to metagenome sequences. I wanted to try classification and binning but from the readme description, it is unclear how to use them. 

`python eval_binning.py --test_model_dir ${MODEL_DIR} --data_dir ${DATA_DIR} --model_list "test"`

What should be there in DATA_DIR, is it only a CSV file containing paired sequences or something else? If I want to get embeddings of metagenome sequences and I don't have pairs, is it applicable to have same sequences as pairs for input?

What should be MODEL_DIR? I have unzipped the DNABERT-S folder (from this `gdown 1p59ch_MO-9DXh3LUIvorllPJGLEAwsUp`). In the zip file, I find only pytorch_model.bin and no head_weights.ckpt or cons_weights.ckpt files. Do we not need them for classification or binning?

Thank you.

**Comment by Zhihan1996** [comment]
Hey,

Please set `MODEL_DIR` as the path to the folder contains `pytorch_model.bin`, something like `/home/user/model/DNABERT-S`.

For the data, please download the evaluation data use gdown as documented in README, and set `DATA_DIR` as the path of the unzipped folder.
