### ISSUE TITLE
How to get embeddings for long sequences?

### ISSUE THREAD

**Issue by yazhinia** [MAGICS-LAB/DNABERT_S#16]
I wanted to get embeddings for longer sequences (which can be >20kb). I can segment sequences and get embeddings for each segment. Do you have an idea of how to combine embeddings of segments to give one embedding vector for each sequence?
Also, I suppose, `test` model among seven models is the one I  should use for embeddings. If so, I can't find a pre-trained model and corresponding weights in this repository. Is `pytorch_model.bin` is the model I should go with?
 
Thank you for your time and effort to answer my questions.

**Comment by Zhihan1996** [comment]
You can try two ways,

1. If your sequences are not crazily long (e.g., over 100k), you can directly generate embedding for the entire sequence at once. The model theoretically supports unlimited input length. The actual length limits are only bounded by your GPU memory.
2. You can split your sequence into 20kb segments, either overlapping or non-overlapping (you may wanna test both), generate embedding for each segment, and take the average or dimension-wise maximum (you may also wanna test both).

The pre-trained model is on Huggingface named `zhihan1996/DNABERT-S`. You can directly use it with

`model = AutoModel.from_pretrained("zhihan1996/DNABERT-S", trust_remote_code=True)`
