### ISSUE TITLE
Error when using --con_method mutate

### ISSUE THREAD

**Issue by Wesady** [MAGICS-LAB/DNABERT_S#17]
HI!
When I try to change `con_method` to `mutate`, I get an error
```LookupError: 
**********************************************************************
  Resource stopwords not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('stopwords')
  
  For more information see: https://www.nltk.org/data.html
```
should I do just as the prompt? THANK YOU~

**Comment by WeiminWu2000** [comment]
Hi, thanks for your interest in our work. 
I think this bug is related to the installment or version of the library textaugment.
Please refer to https://github.com/nltk/nltk/issues/3063. 
If you still have problem, please feel free to contact me.

**Comment by Wesady** [comment]
Thank you
