### ISSUE TITLE
Questions about tokenizer

### ISSUE THREAD

**Issue by HelloWorldLTY** [MAGICS-LAB/DNABERT_S#18]
Hi, I take a look at the tokenizer file and found that the length of each token is not 6, which is different from DNABERT. I did not find the description of such tokenization technique in the manuscript.  I wonder if you can share about your idea of choosing such new design or not, which could be really helpful. Thanks a lot.

**Comment by Zhihan1996** [comment]
Hey,

In DNABERT-S, we use the same BPE tokenizer introduced in the DNABERT-2 paper. Please check Sections 2 and 3.1 of the [DNABERT-2 paper](https://arxiv.org/pdf/2306.15006) for more information.
