### ISSUE TITLE
Encountering problems using freshly installed DNABERT-S

### ISSUE THREAD

**Issue by cerebis** [MAGICS-LAB/DNABERT_S#19]
I have used DNABERT-S in the past using a conda environment, however today, when I try a fresh install I am getting an error within the triton package during compilation.

```TypeError("dot() got an unexpected keyword argument 'trans_b'")```

This appears to be due to an API change since the release of DNABERT-S, and there is a suggested fix to this widespread problem.

I have managed to get around the error by version pinning the following package:

- `triton==2.0.0.dev20221202`

I hope that these very specific versions are not necessary.

Perhaps DNABERT-S has not been kept in sync with `zhihan1996/DNABERT-2-117M`?

I attempted to specify a revision of the parent, but could not resolve the error until I pinned those versions mentioned.

**Comment by cerebis** [comment]
To continue this issue, simply removing triton resolves the issue.

I see within the DNABERT-S model, that there is an optional implementation of flash-attention which gets ignored when triton doesn't exist.

**Comment by cerebis** [comment]
I've dug into triton's documentation and release history.

I found that using the release:"legacy-backend", which predates change to MLIR, resolves the issue. I have not verified if  DNABERT-S then uses flash-attention, but at least it doesn't throw an error.

Pulling this release from PyPi is not possible, but this might be the reason for the version I first mentioned. The "legacy-backend" release was out on 21/12/2022.

**Comment by Zhihan1996** [comment]
Thanks for sharing all the findings! Personally, I find the flash-attention implementation works well on GPUs with NVIDIA Ampere Architecture (e.g., A100) but can have various problems when using older GPUs.
