### ISSUE TITLE
Error loading model with AutoModel

### ISSUE THREAD

**Issue by rnowling** [MAGICS-LAB/DNABERT_S#20]
When trying to load DNABERT-S from HuggingFace, the following error is generated:

```
ValueError: The model class you are passing has a `config_class` attribute that is not consistent with the config class you passed (model has <class 'transformers.models.bert.configuration_bert.BertConfig'> and you passed <class 'transformers_modules.zhihan1996.DNABERT-S.1cdf84d992ace6f3e75c7356774b4da088c8dc7c.configuration_bert.BertConfig'>. Fix one of those so they match!
```

Another user suggested a [fix](https://huggingface.co/zhihan1996/DNABERT-S/commit/3263bb1e2dd26b172d2e21beba67da74818e61d9).  This fix probably needs to be applied and the model re-uploaded.

**Comment by Zhihan1996** [comment]
Can you try `pip install transformers==4.28`? This is  a issue from the Huggingface Transformer package

**Comment by rnowling** [comment]
Pinning the version isn’t a good long-term fix.  If you follow the link, another user has provided a good long-term fix.  Once applied, the model can be re-uploaded to HuggingFace and used with any version of the library.

**Comment by Zhihan1996** [comment]
Thanks for sharing! I didn't notice the fix. I have merged it.
