### ISSUE TITLE
Evaluation on private data

### ISSUE THREAD

**Issue by gth-ai** [MAGICS-LAB/DNABERT_S#21]
Hello team,
Thank you for your excellent work.

In the evaluation section, you show how to evaluate the model on the data you propose.
But if I train the base model on my own data, I logically have to test the resulting model on my own test data.
Is it possible to describe how to prepare the test data in the case of using our own data?

Thanks.

**Comment by Zhihan1996** [comment]
Thanks for using our model!

If you are doing the same species differentiation as us, the benchmark dataset we provide should be a good start for you. If you are building a model towards another goal, you need to prepare the data for your evaluation. To start, you can perform clustering and classifications with our scripts. To generate the data, you just find different groups (e.g., species in our case) of sequences and create a balanced subset of it. You may need to choose the appropriate sequence lengths based on your task. If you wanna use our codes, you can process the data into the same format as ours, which is very standard.
