### ISSUE TITLE
Progress bar not updating per epoch

### ISSUE THREAD

**Issue by LukasMahieu** [MAGICS-LAB/DNABERT_S#3]
I'm not sure if you intended this behavior, maybe you only want to see the progress bar updating in the first epoch, but currently the progress bar is not being reset inside the train() function

So, this:
```python
epoch_iterator = tqdm(self.train_loader, desc="Iteration")
for epoch in range(self.args.epochs):
    if self.curriculum:
```

Should be this (if you want the reset each epoch, which I think you do)
```python
for epoch in range(self.args.epochs):
    epoch_iterator = tqdm(self.train_loader, desc="Iteration")
    if self.curriculum:
```

**Comment by WeiminWu2000** [comment]
Thanks for your correction.
