### ISSUE TITLE
question about config_class

### ISSUE THREAD

**Issue by jinz2014** [MAGICS-LAB/DNABERT_S#4]
Running the program in your README shows the following error. Thanks for your instruction.

```
import torch
from transformers import AutoTokenizer, AutoModel

tokenizer = AutoTokenizer.from_pretrained("zhihan1996/DNABERT-S", trust_remote_code=True)
model = AutoModel.from_pretrained("zhihan1996/DNABERT-S", trust_remote_code=True)
```

ValueError: The model class you are passing has a `config_class` attribute that is not consistent with the config class you passed (model has <class 'transformers.models.bert.configuration_bert.BertConfig'> and you passed <class 'transformers_modules.zhihan1996.DNABERT-S.1cdf84d992ace6f3e75c7356774b4da088c8dc7c.configuration_bert.BertConfig'>. Fix one of those so they match!

**Comment by Zhihan1996** [comment]
Hey,

This is due to the recent updates of the transformers package. This code should work with `transformers==4.28`.
